export type Engine = {
  url: string
  name: string
  iframe?: boolean
}
export const defaultEngines: readonly Engine[] = Object.freeze([
  {name: 'Steam', url: 'https://store.steampowered.com/search/?term=%s'},
  {name: 'Urban', url: 'https://www.urbandictionary.com/define.php?term=%s', iframe: true},
  {name: 'WolframAlpha', url: 'https://www.wolframalpha.com/input/?i=%s'},
  {name: 'Google Images', url: 'https://www.google.com/search?tbm=isch&q=%s'},
  {name: 'Google Maps', url: 'https://www.google.com/maps/search/%s'},
  {name: 'Google Translate', url: 'https://translate.google.com/?sl=auto&tl=en&text=%s'},
  {name: 'Dict', url: 'https://www.dict.cc/?s=%s', iframe: true},
  {name: 'Brave', url: 'https://search.brave.com/search?q=%s'},
  {name: 'Ecosia', url: 'https://www.ecosia.org/search?q=%s'},
  {
    name: 'GMX',
    url: 'https://search.gmx.com/web/result?q=%s&origin=web&comp=web_start_sf&p=gmx-com',
  },
  {
    name: 'Wikipedia',
    url: 'https://en.wikipedia.org/w/index.php?title=Special:Search&search=%s',
    iframe: true,
  },
  {name: 'MDN', url: 'https://developer.mozilla.org/search?q=%s'},
  {name: 'Duden', url: 'https://www.duden.de/suchen/dudenonline/%s'},
  {name: 'DIGITAL.CSIC', url: 'https://digital.csic.es/simple-search?query=%s'},
  {name: 'SoundCloud', url: 'https://soundcloud.com/search?q=%s'},
  {
    name: 'Python',
    url: 'https://docs.python.org/3/search.html?q=%s&check_keywords=yes&area=default',
    iframe: true,
  },
  {name: 'Git', url: 'https://git-scm.com/search/results?search=%s'},
  {name: 'PyPI', url: 'https://pypi.org/search/?q=%s'},
  {name: 'CTAN', url: 'https://ctan.org/search?phrase=%s', iframe: true},
  {name: 'tex.stackexchange', url: 'https://tex.stackexchange.com/search?q=%s'},
  {name: 'Google Scholar', url: 'https://scholar.google.at/scholar?q=%s'},
  {name: 'Searchalot', url: 'https://www.searchalot.com/?q=%s'},
  {name: 'DuckDuckGo', url: 'https://duckduckgo.com/?q=%s'},
  {name: 'DuckDuckLight', url: 'https://lite.duckduckgo.com/lite/?q=%s'},
  {name: 'matplotlib', url: 'https://matplotlib.org/stable/search.html?q=%s', iframe: true},
  {name: 'pandas', url: 'https://pandas.pydata.org/docs/search.html?q=%s', iframe: true},
  {name: 'who.is', url: 'https://who.is/whois-ip/ip-address/%s', iframe: true},
  {name: 'Yarn', url: 'https://yarnpkg.com/?q=%s', iframe: true},
  {name: 'GitHub', url: 'https://github.com/search?q=%s&ref=opensearch'},
  {name: 'Stack Overflow', url: 'https://stackoverflow.com/search?q=%s'},
  {name: 'YouTube', url: 'https://www.youtube.com/results?search_query=%s'},
  {name: 'amazon.de', url: 'https://www.amazon.de/s?k=%s'},
  {name: 'Google', url: 'https://www.google.com/search?q=%s'},
  {name: 'Bing', url: 'https://www.bing.com/search?q=%s', iframe: true},
  {name: 'Reddit', url: 'https://www.reddit.com/search/?q=%s'},
  {name: 'Yandex', url: 'https://yandex.com/search/?text=%s'},
  {name: 'Qwant', url: 'https://www.qwant.com/?q=%s'},
  {name: 'Swisscows', url: 'https://swisscows.com/web?query=%s', iframe: true},
  {name: 'IMDb', url: 'https://www.imdb.com/find?q=%s'},
  {name: 'Rotten Tomatoes', url: 'https://www.rottentomatoes.com/search?search=%s'},
  {name: 'Spotify', url: 'https://open.spotify.com/search/%s'},
  {name: 'eBay', url: 'https://www.ebay.com/sch/i.html?_nkw=%s'},
  {name: 'Smashing Magazine', url: 'https://www.smashingmagazine.com/search/?q=%s'},
  {name: 'A List Apart', url: 'https://alistapart.com/?s=%s'},
  {name: 'CodePen', url: 'https://codepen.io/search/pens?q=%s'},
  {name: 'Dev.to', url: 'https://dev.to/search?q=%s'},
  {name: 'CodeSandbox', url: 'https://codesandbox.io/search?query=%s', iframe: true},
  {name: 'Bitbucket', url: 'https://bitbucket.org/repo/all?name=%s'},
  {name: 'Vimeo', url: 'https://vimeo.com/search?q=%s'},
  {name: 'Dailymotion', url: 'https://www.dailymotion.com/search/%s', iframe: true},
  {name: 'Twitch', url: 'https://www.twitch.tv/search?term=%s'},
  {name: 'X', url: 'https://x.com/search?q=%s'},
  {name: 'Medium', url: 'https://medium.com/search?q=%s'},
  {name: 'Khan Academy', url: 'https://www.khanacademy.org/search?page_search_query=%s'},
  {name: 'Stack Exchange', url: 'https://stackexchange.com/search?q=%s'},
  {name: 'npm', url: 'https://www.npmjs.com/search?q=%s'},
  {name: 'Packagist', url: 'https://packagist.org/search/?q=%s'},
  {name: 'Docker Hub', url: 'https://hub.docker.com/search?q=%s'},
  {
    name: 'Wiktionary',
    url: 'https://en.wiktionary.org/wiki/Special:Search?search=%s',
    iframe: true,
  },
  {name: 'Metacritic', url: 'https://www.metacritic.com/search/%s', iframe: true},
  {name: 'My Abandonware', url: 'https://www.myabandonware.com/search/q/%s', iframe: true},
])
